import { CardData } from './types';

export const ARENA = {
  width: 400,
  height: 600,
  bridgeWidth: 60,
  riverY: 300,
  riverHeight: 40,
};

export const TICK_RATE = 100; // 10 ticks per second
export const MATCH_DURATION = 180; // 3 minutes
export const ELIXIR_RATE = 1; // 1 elixir per second
export const MAX_ELIXIR = 10;

export const CARDS: Record<string, CardData> = {
  knight: {
    id: 'knight',
    name: 'Knight',
    cost: 3,
    hp: 1400,
    damage: 150,
    range: 20,
    speed: 40,
    attackSpeed: 1100,
    color: '#8b5a2b',
    emoji: '🤺',
    rarity: 'Common',
  },
  archer: {
    id: 'archer',
    name: 'Archer',
    cost: 3,
    hp: 300,
    damage: 80,
    range: 120,
    speed: 45,
    attackSpeed: 1000,
    color: '#ff69b4',
    emoji: '🏹',
    rarity: 'Common',
  },
  giant: {
    id: 'giant',
    name: 'Giant',
    cost: 5,
    hp: 2500,
    damage: 120,
    range: 30,
    speed: 25,
    attackSpeed: 1500,
    targetsBuildingsOnly: true,
    color: '#cd853f',
    emoji: '🧟',
    rarity: 'Rare',
  },
  goblin: {
    id: 'goblin',
    name: 'Goblin',
    cost: 2,
    hp: 200,
    damage: 60,
    range: 20,
    speed: 60,
    attackSpeed: 800,
    color: '#32cd32',
    emoji: '👺',
    rarity: 'Common',
  },
  wizard: {
    id: 'wizard',
    name: 'Wizard',
    cost: 5,
    hp: 600,
    damage: 180,
    range: 100,
    speed: 40,
    attackSpeed: 1400,
    color: '#9333ea',
    emoji: '🧙‍♂️',
    rarity: 'Rare',
  },
  skeleton: {
    id: 'skeleton',
    name: 'Skeleton',
    cost: 1,
    hp: 100,
    damage: 40,
    range: 20,
    speed: 70,
    attackSpeed: 700,
    color: '#d1d5db',
    emoji: '💀',
    rarity: 'Common',
  },
  valkyrie: {
    id: 'valkyrie',
    name: 'Valkyrie',
    cost: 4,
    hp: 1600,
    damage: 140,
    range: 25,
    speed: 45,
    attackSpeed: 1200,
    color: '#f97316',
    emoji: '🪓',
    rarity: 'Rare',
  },
  musketeer: {
    id: 'musketeer',
    name: 'Musketeer',
    cost: 4,
    hp: 600,
    damage: 160,
    range: 150,
    speed: 40,
    attackSpeed: 1100,
    color: '#6366f1',
    emoji: '🔫',
    rarity: 'Rare',
  },
  hog_rider: {
    id: 'hog_rider',
    name: 'Hog Rider',
    cost: 4,
    hp: 1400,
    damage: 200,
    range: 25,
    speed: 75,
    attackSpeed: 1500,
    targetsBuildingsOnly: true,
    color: '#b45309',
    emoji: '🐗',
    rarity: 'Rare',
  },
  mini_pekka: {
    id: 'mini_pekka',
    name: 'Mini P.E.K.K.A',
    cost: 4,
    hp: 1100,
    damage: 350,
    range: 25,
    speed: 60,
    attackSpeed: 1600,
    color: '#374151',
    emoji: '🤖',
    rarity: 'Rare',
  },
  bomber: {
    id: 'bomber',
    name: 'Bomber',
    cost: 3,
    hp: 300,
    damage: 150,
    range: 90,
    speed: 45,
    attackSpeed: 1800,
    color: '#ef4444',
    emoji: '💣',
    rarity: 'Common',
  },
  balloon: {
    id: 'balloon',
    name: 'Balloon',
    cost: 5,
    hp: 1400,
    damage: 400,
    range: 20,
    speed: 35,
    attackSpeed: 3000,
    targetsBuildingsOnly: true,
    color: '#0ea5e9',
    emoji: '🎈',
    rarity: 'Epic',
  }
};
